{
 "title": "Rumbl",
 "time": { "from": "2019-04-04T15:44:00.000Z", "to": "2019-04-04T15:57:01.000Z" },
 "panels": [
  {
   "title": "VM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total memory",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "kind" ], "type": "tag" }
       ],
       "measurement": "vm_memory",
       "query": "SELECT last(\"value\") FROM \"vm_memory\" WHERE $timeFilter GROUP BY time($__interval), \"kind\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "kind", "operator": "=", "value": "total" }
       ]
      }
     ]
    },
    {
     "title": "Memory used by type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 5, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_kind",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "kind" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "vm_memory",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "kind", "operator": "!=", "value": "total" }
       ]
      }
     ]
    },
    {
     "title": "Run queue lengths",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_kind",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "kind" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "vm_total_run_queue_lengths",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "kind", "operator": "!=", "value": "io" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP request/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "count",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "http_requests",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP response count by status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 5, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "status: $tag_status",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "http_responses",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "app", "operator": "=", "value": "rumbl" },
        { "condition": "AND", "key": "status", "operator": "!=", "value": "302" }
       ]
      }
     ]
    },
    {
     "title": "99th percentile response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "status: $tag_status",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "http_responses",
       "select": [
        [
         { "params": [ "duration_99_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "!=", "value": "302" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Phoenix Controllers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller calls/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_controller.$tag_action",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "controller" ], "type": "tag" },
        { "params": [ "action" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "controller_calls",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "99th percentile controller time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_controller.$tag_action: $tag_status",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "controller" ], "type": "tag" },
        { "params": [ "action" ], "type": "tag" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "controller_calls",
       "select": [
        [
         { "params": [ "duration_99_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "!=", "value": "302" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB queries/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "table: $tag_source",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "db_query",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "99th percentile DB query time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "table: $tag_source",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "db_query",
       "select": [
        [
         { "params": [ "total_time_99_percentile" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}