version: "3"
services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
  graphite_statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - "8080:80"
      - "2003:2003"
      - "8126:8126"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./volumes/grafana:/var/lib/grafana"
